--- #YAML:1.0
name: SjisTk
abstract: Tk modules on Microsoft Windows with Sjis software
version: 0.01
author:
  - INABA Hitoshi <ina@cpan.org>
license: perl
distribution_type: script
requires:
  Sjis: 0.63
  Archive::Tar: 0.072
  Carp: 0
  Compress::Zlib: 1.03
  Config: 0
  Encode: 2.26
  Fcntl: 1.03
  File::Basename: 2.6
  File::Copy: 2.02
  File::Path: 1.0401
  FindBin: 1.42
  Getopt::Std: 1.01
  Symbol: 0
  Test: 1.122
  Test::Harness: 1.1602
  perl: 5.005_03
  Win32: 0.151
recommends:
  Tk: 800.022
build_requires:
  Test: 1.122
urls:
  license: http://dev.perl.org/licenses/
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by: INABA Hitoshi <ina@cpan.org>
